#pragma once

#include <cstdint>

/**
 * Build-time-emitted catalog of (file_id, byte_offset_in_file, family) tuples
 * advertising "torch already applied this portFixup* helper's byte transform
 * during extraction." Generated by tools/generate_struct_fixup_catalog.py from
 * port/test/struct_fixup_catalog.json (collected via SSB64_FIXUP_CAPTURE=1
 * runs).
 *
 * Each portFixup* helper consults the catalog before running its byte
 * transform body; if (a) the catalog has the matching tuple AND (b) the
 * file's RelocFile::ProcessingFlags has the matching PROC_<FAMILY>_DONE bit
 * set, the helper skips the transform but still records the call in its
 * heap-absolute idempotency tracker (sStructU16Fixups). Both gates required
 * so a torch SHA that drops a tuple cannot silently corrupt data — the
 * catalog miss falls back to the runtime transform regardless of flag state.
 *
 * `family` values match the PROC_<FAMILY>_DONE bit numbers in RelocFile.h:
 *   2 = STRUCT_U16, 3 = STRUCT_U32, 4 = SPRITE,
 *   5 = BITMAP,    6 = MOBJSUB,    7 = FTATTRIBUTES.
 */

#ifdef __cplusplus
extern "C" {
#endif

bool portStructFixupCatalogHasEntry(int file_id, uint32_t byte_offset, uint8_t family);

#ifdef __cplusplus
}
#endif
