#!/usr/bin/env python3
"""
generate_struct_fixup_catalog.py — Reads port/test/struct_fixup_catalog.json
and generates port/resource/StructFixupCatalog.cpp, a sorted constexpr
table of (family, file_id, byte_offset_in_file, extra) tuples that the
runtime queries to decide whether torch already applied a portFixup*
helper's byte transform at extraction time.

Source JSON shape: a flat array of 4-tuples
    [[family, file_id, byte_offset, extra], ...]
where family is the PROC_<FAMILY>_DONE bit number (2..7) and extra carries
num_words for U16/U32 entries (0 for fixed-size struct families).

Generated by SSB64_FIXUP_CAPTURE=1 runs of the game; see docs/refactor_buildtime_reloc_handoff.md
Stage 6a for capture mechanics.

Usage:
    python tools/generate_struct_fixup_catalog.py
"""

import json
import os
import sys
from pathlib import Path

INPUT  = Path("port/test/struct_fixup_catalog.json")
OUTPUT = Path("port/resource/StructFixupCatalog.cpp")

FAMILY_NAMES = {
    2: "STRUCT_U16",
    3: "STRUCT_U32",
    4: "SPRITE",
    5: "BITMAP",
    6: "MOBJSUB",
    7: "FTATTRIBUTES",
}


def encode_key(family: int, file_id: int, byte_offset: int) -> int:
    """Pack (family, file_id, byte_offset) into a single u64. Mirrors the
    encoding in lbreloc_byteswap.cpp::capture_emit so the runtime's lookup
    set uses the same shape."""
    return (family << 56) | (file_id << 32) | byte_offset


def main() -> None:
    os.chdir(Path(__file__).resolve().parent.parent)

    if not INPUT.exists():
        print(f"WARNING: {INPUT} not found; emitting empty catalog", file=sys.stderr)
        tuples = []
    else:
        with INPUT.open("r", encoding="utf-8") as f:
            tuples = json.load(f)

    # Validate, dedup, sort.
    seen: dict[int, tuple] = {}
    for t in tuples:
        if not (isinstance(t, list) and len(t) == 4):
            sys.exit(f"bad catalog entry shape: {t!r}")
        family, file_id, byte_offset, extra = t
        if family not in FAMILY_NAMES:
            sys.exit(f"unknown family bit {family} (expected 2..7) in {t!r}")
        if not (0 <= file_id < (1 << 16)):
            sys.exit(f"file_id out of range in {t!r}")
        if not (0 <= byte_offset < (1 << 32)):
            sys.exit(f"byte_offset out of range in {t!r}")
        key = encode_key(family, file_id, byte_offset)
        # Dedup: take max(extra) if a tuple shows up twice with different extras
        # (covers the case where a U16 fixup widens after capture)
        if key in seen and seen[key][3] != extra:
            print(f"NOTE: dedup conflict on {t!r}: prev extra={seen[key][3]}, new={extra}; "
                  f"taking max", file=sys.stderr)
            extra = max(seen[key][3], extra)
        seen[key] = (family, file_id, byte_offset, extra)

    sorted_tuples = sorted(seen.values())

    # Family histogram for the header comment
    family_counts: dict[int, int] = {f: 0 for f in FAMILY_NAMES}
    for fam, _, _, _ in sorted_tuples:
        family_counts[fam] += 1

    # Per-file index breakpoints — the runtime can binary-search inside one
    # file's slice instead of searching the whole array.
    file_slices: list[tuple[int, int, int]] = []  # (file_id, start, end)
    if sorted_tuples:
        cur_file = sorted_tuples[0][1]
        cur_start = 0
        for i, (_, fid, _, _) in enumerate(sorted_tuples):
            if fid != cur_file:
                file_slices.append((cur_file, cur_start, i))
                cur_file = fid
                cur_start = i
        file_slices.append((cur_file, cur_start, len(sorted_tuples)))

    lines: list[str] = []
    lines.append("/**")
    lines.append(" * StructFixupCatalog.cpp - Auto-generated portFixup* dispatch catalog.")
    lines.append(" *")
    lines.append(" * Source: port/test/struct_fixup_catalog.json")
    lines.append(" * Generator: tools/generate_struct_fixup_catalog.py")
    lines.append(" * DO NOT EDIT BY HAND.")
    lines.append(" *")
    lines.append(" * Family histogram (PROC_<FAMILY>_DONE bit → entry count):")
    for fam, name in sorted(FAMILY_NAMES.items()):
        lines.append(f" *   {fam} {name:<14} {family_counts[fam]:>6}")
    lines.append(f" * Total entries: {len(sorted_tuples)}")
    lines.append(" */")
    lines.append("")
    lines.append('#include "StructFixupCatalog.h"')
    lines.append("")
    lines.append("#include <algorithm>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace {")
    lines.append("")
    lines.append("// Each entry packs (family<<56)|(file_id<<32)|byte_offset_in_file.")
    lines.append("// Sorted ascending so the lookup uses std::binary_search.")
    lines.append(f"constexpr uint64_t kEntries[] = {{")
    if sorted_tuples:
        for fam, fid, off, _extra in sorted_tuples:
            key = encode_key(fam, fid, off)
            lines.append(f"    UINT64_C(0x{key:016X}),  // fam={fam} fid={fid} off={off}")
    else:
        lines.append("    /* empty catalog — runtime applies all fixup byte transforms */")
    lines.append("};")
    lines.append("")
    lines.append(f"constexpr size_t kEntryCount = {len(sorted_tuples)};")
    lines.append("static_assert(sizeof(kEntries) / sizeof(kEntries[0]) == kEntryCount,")
    lines.append('              "kEntries length must match kEntryCount");')
    lines.append("")
    lines.append("}  // namespace")
    lines.append("")
    lines.append("extern \"C\" bool portStructFixupCatalogHasEntry(int file_id, uint32_t byte_offset, uint8_t family)")
    lines.append("{")
    lines.append("    if (file_id < 0 || file_id >= (1 << 16) || family < 2 || family > 7)")
    lines.append("        return false;")
    lines.append("    const uint64_t key = (uint64_t(family) << 56)")
    lines.append("                       | (uint64_t(uint32_t(file_id)) << 32)")
    lines.append("                       | uint64_t(byte_offset);")
    lines.append("    return std::binary_search(kEntries, kEntries + kEntryCount, key);")
    lines.append("}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    summary = ", ".join(f"{FAMILY_NAMES[f]}={n}" for f, n in sorted(family_counts.items()) if n)
    if not summary:
        summary = "empty"
    print(f"Generated {OUTPUT} ({len(sorted_tuples)} entries: {summary})")


if __name__ == "__main__":
    main()
